name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run typecheck
      - run: npm run lint
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry && cd apps/api && poetry install
      - run: cd apps/api && poetry run pytest
